# Redirect domain to primary brand domain
server {
    listen 80;
    server_name gochinamedtrip.com www.gochinamedtrip.com;
    return 301 https://dentaltripchina.com$request_uri;
}

server {
    listen 443 ssl http2;
    server_name gochinamedtrip.com www.gochinamedtrip.com;

    ssl_certificate     /etc/letsencrypt/live/gochinamedtrip.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gochinamedtrip.com/privkey.pem;

    return 301 https://dentaltripchina.com$request_uri;
}
